name: Unit Tests # name of the test

on:
 push:
   branches: [ main ]  # or 'master' if that's your primary branch name
 pull_request:
   branches: [ main ] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
 tests: # the name of your status check, will become important when you do branch protection
   runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
   steps:
     - uses: actions/checkout@v4 # using version 4 of Actions
     # Lab 2
     - name: Install Dependencies for Lab 2
       working-directory: ./lab2/my-app
       run: npm install
     - name: Unit Test for Lab 2
       working-directory: ./lab2/my-app
       run: npm test # the actual testing line
     # Lab 3
     - name: Install Dependencies for Lab 3
       working-directory: ./lab3
       run: npm install
     - name: Unit Test for Lab 3
       working-directory: ./lab3
       run: npm test # the actual testing line
     # Lab 4
     - name: Install Dependencies for Lab 4
       working-directory: ./lab4
       run: npm install
     - name: Unit Test for Lab 4
       working-directory: ./lab4
       run: npm test # the actual testing line
     
     
